### ISSUE TITLE
Error with ASCII encode

### ISSUE THREAD

**Issue by 2600box** [corpnewt/EssentialsList#3]
On Mojave with updated brew and Xcode-tools, I get the following ASCII encode error and no file is produced.

```
  #######################################################
 #                  Gathering Info                     #
#######################################################
 
Got Clover install at /Volumes/EFI/EFI/CLOVER (disk0s1)
 
Locating serial for obfuscation...
Getting Clover info from /Volumes/EFI/EFI/CLOVER...
NO APPLICABLE DEBUG.LOG FOUND IN MISC!
  SET CONFIG -> BOOT -> DEBUG = TRUE AND REBOOT TO DUMP
NO APPLICABLE PREBOOT.LOG FOUND IN MISC!
  REBOOT AND PRESS F2 IN CLOVER TO DUMP
NO APPLICABLE SSDT/DSDT FILES FOUND IN ACPI -> ORIGIN!
  REBOOT AND PRESS F4 IN CLOVER TO DUMP
Getting diskutil list...
Getting mounted volumes...
Getting nvram...
Getting bdmesg...
Something went wrong!
'ascii' codec can't encode characters in position 6884-6889: ordinal not in range(128)
Unmounting EFI partition...
 
Done!^CTraceback (most recent call last):
  File "./EssentialsList.command", line 778, in <module>
    e.main()
  File "./EssentialsList.command", line 321, in main
    self.u.grab("Done!", timeout=5)
  File "/Users/sloopbun/EssentialsList/Scripts/utils.py", line 180, in grab
    i, o, e = select.select( [sys.stdin], [], [], timeout )
KeyboardInterrupt

```

**Comment by corpnewt** [comment]
Hmmm - looks like there's some unicode character in your bdmesg that's causing issues (py2 has tons of issues with unicode).  Could you run the following in terminal, and send me the resulting bdmesg.txt:
```sh
ioreg -l -p IODeviceTree -w0 | grep boot-log | cut -d'<' -f2 | cut -d'>' -f1 | xxd -r -p > ~/Desktop/bdmesg.txt
```
In the meantime, I'll see if there's any other unicode bulletproofing I can do.

-CorpNewt

---

Could I also get the resulting bdmesg_hex.txt from the following:
```sh
ioreg -l -p IODeviceTree -w0 | grep boot-log | cut -d'<' -f2 | cut -d'>' -f1 > ~/Desktop/bdmesg_hex.txt
```
